### ISSUE TITLE
Improve Readability for Collaborators

### ISSUE THREAD

**Issue by Reader8765** [pydude/Stikk.io#38]
I would like to try to make some pull requests, but the code isn't commented and organized for that.
Also, I'm sorry if I am coming across as pushy by submitting so many issues. The game is great!

**Comment by pydude** [comment]
Yeah, the code it really bad in some parts. Adding issues is good because it lets me see bugs I might not catch otherwise, and gives new opinions. 

However, as for pull requests and things...
I don't plan to accept any pull requests. I want the game to be made completely by me, without help from others. Honestly, the only reason this is on GitHub is because it is required by my server hosting provider. 
Keep playing and providing feedback on it, but I don't want parts of the code to be from other people. Sorry about that.
